env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  Jdbc {
    plugin_output = "mysql_wms"
    url = "jdbc:mysql://192.168.0.151:3306/saas_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8"
    driver = "com.mysql.cj.jdbc.Driver"
    connection_check_timeout_sec = 100
    user = "root"
    password ="Aa123456!"
    query = """SELECT
               itm.item_id,
               b.bill_id AS bill_id,
               b.bill_date AS bill_time,
               b.tenant_id,
               b.warehouse_id,
               b.org_id,
               b.store_id,
               COALESCE(b.town_code, b.city_code, b.province_code, 'UNKNOWN') AS area_code,
               b.plat_code AS channel_code,
               itm.product_id,
               itm.sku_id,
               itm.discount,
               itm.qty,
               itm.price,
               itm.amt,
               p.tag_price,
               itm.qty * p.tag_price AS tag_price_amt,
               p.retail_price,
               itm.qty * p.retail_price AS retail_price_amt,
               CURRENT_TIMESTAMP AS etl_dt
             FROM
               tf_wms_bill_delivery_notice b
               JOIN tf_wms_bill_delivery_notice_item itm ON b.bill_id = itm.bill_id
               LEFT JOIN v_tdw_prd_product p ON itm.product_id = p.product_id
             WHERE
               b.bill_status = 5
               AND b.deal_status IN (1, 2)"""
  }
}

transform {
  Sql {
    plugin_input = "mysql_wms"
    plugin_output = "paimon_wms"
    query = """SELECT CAST(item_id as BIGINT) as item_id,
        bill_time,
        CAST(bill_id as BIGINT) as bill_id,
        CAST(tenant_id as BIGINT) as tenant_id,
        CAST(warehouse_id as BIGINT) as warehouse_id,
        CAST(org_id as BIGINT) as org_id,
        CAST(store_id as BIGINT) as store_id,
        area_code, channel_code,
        CAST(product_id as BIGINT) as product_id,
        CAST(sku_id as BIGINT) as sku_id,
        discount, qty, price, amt, tag_price, tag_price_amt,
        retail_price, retail_price_amt, '20250208' as dt, etl_dt
        FROM mysql_wms"""
  }
}

sink {
  Paimon {
    warehouse = "hdfs:///saas_dw"
    database = "dwd"
    table = "dwd_seatunnel_test"
    overwrite = {
        dt = "20250208"
    }
    paimon.hadoop.conf = {
      fs.defaultFS = "hdfs://nameservice1"
      dfs.nameservices = "nameservice1"
      dfs.ha.namenodes.nameservice1 = "nn1,nn2,nn3"
      dfs.namenode.rpc-address.nameservice1.nn1 = "hadoop001:8020"
      dfs.namenode.rpc-address.nameservice1.nn2 = "hadoop002:8020"
      dfs.namenode.rpc-address.nameservice1.nn3 = "hadoop003:8020"
      dfs.client.failover.proxy.provider.nameservice1 = "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
      dfs.client.use.datanode.hostname = "true"
    }
  }
}
